### ISSUE TITLE
grpc api raises internal error

### ISSUE THREAD

**Issue by martinbe1io** [chirpstack/chirpstack#303]
Hi, 

migrating from chirpstack 3.0 to 4.0 I had to update my java based api layer as well, connecting to chirpstack 4 raises an error 

```
	at java.base/java.lang.Thread.run(Thread.java:829)

[2023-10-21 10:26:00,182]-[JobFactory-jobexecution-8a08151c-ea0d-43ff-a6df-c49c008af578] ERROR io.be1.circular.externalassets.ExternalAssetProviderChirpStack - an error occured: afterupdatestatus io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
[2023-10-21 10:26:00,184]-[JobFactory-jobexecution-8a08151c-ea0d-43ff-a6df-c49c008af578] ERROR io.be1.circular.externalassets.ExternalAssetProviderChirpStack - stacktrace: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at io.chirpstack.api.InternalServiceGrpc$InternalServiceBlockingStub.login(InternalServiceGrpc.java:1004)
	at io.be1.circular.externalassets.ExternalAssetProviderChirpStack.getChirpApiChannel(ExternalAssetProviderChirpStack.java:671)
	at io.be1.circular.externalassets.ExternalAssetProviderChirpStack.registerDevice(ExternalAssetProviderChirpStack.java:694)
	at io.be1.circular.externalassets.ExternalAssetProviderChirpStack.afterUpdatestatus(ExternalAssetProviderChirpStack.java:474)
	at io.be1.circular.externalassets.ExternalAssetProviderBase.updateStatus(ExternalAssetProviderBase.java:721)
	at io.be1.circular.externalassets.ExternalAssetProviderBase.updateStatus(ExternalAssetProviderBase.java:643)
	at io.be1.circular.externalassets.ExternalAssetManagerModule.deployExternalAsset(ExternalAssetManagerModule.java:1062)
	at io.be1.circular.assets.AssetsMvcBase.deployExternalAsset(AssetsMvcBase.java:1561)
	at io.be1.circular.assets.AssetsMvcBase.deployExternalAssets(AssetsMvcBase.java:1447)
	at io.be1.circular.assets.AssetsMvcBase.create(AssetsMvcBase.java:4424)
	at io.be1.circular.assets.AssetsMvcBase.handleJob(AssetsMvcBase.java:4533)
	at io.be1.circular.assets.AssetsMvcBase.executeJob(AssetsMvcBase.java:2914)
	at io.be1.circular.platformtools.job.JobFactory.lambda$executejob$1(JobFactory.java:691)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'void io.netty.buffer.PooledByteBufAllocator.<init>(boolean, int, int, int, int, int, int, boolean)'
	at io.grpc.netty.Utils.createByteBufAllocator(Utils.java:180)
	at io.grpc.netty.Utils.access$000(Utils.java:75)
	at io.grpc.netty.Utils$ByteBufAllocatorPreferDirectHolder.<clinit>(Utils.java:98)
	at io.grpc.netty.Utils.getByteBufAllocator(Utils.java:148)
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:233)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1876)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)

```

the relevant code is pretty at the beginning of my business logic and worked well in the 3.0 implementaiton

```
private ManagedChannel getChirpApiChannel() throws Exception 
	{
		if (channel==null)
		{
			if (this.getUsername()==null) throw new Exception("username is null");
			if (this.getPassword()==null) throw new Exception("password is null");
			if (this.getApiurl()==null) throw new Exception("apiurl is null");
			if (this.getTenantId()==null) throw new Exception("tenant id is null");
			if (this.getServiceprofileid()==null) throw new Exception("serviceprofileid is null"); 
			log.info("{} connecting to api host={} port={}",getName(),this.getApiurl().getHost(), this.getApiurl().getPort());
			channel = ManagedChannelBuilder.forAddress(this.getApiurl().getHost(), this.getApiurl().getPort())
				.usePlaintext()
	            .build();

	    InternalServiceGrpc.InternalServiceBlockingStub stub = InternalServiceGrpc.newBlockingStub(channel);

	    
	    LoginRequest loginRequest = LoginRequest.newBuilder()
	            .setEmail(this.getUsername())
	            .setPassword(this.getPassword())
	            .build();

	    LoginResponse loginResponse = stub.login(loginRequest);
	   
	    String token = loginResponse.getJwt(); 
	    btoken=new BearerToken(token);
	  
	   log.info("{} Connection successful", getName());
		}
	    return channel; 
	}
```

any Idea what's wrong, using the following versions

```
<dependency>
  <groupId>io.grpc</groupId>
  <artifactId>grpc-okhttp</artifactId>
  <version>1.51.0</version>
</dependency>

<!-- deployed to my own registry based on latest chirpstack git -->
<dependency>
  <groupId>io.chirpstack</groupId>
  <artifactId>chirpstack-api</artifactId>
  <version>4.5.1</version>
</dependency>
```

**Comment by martinbe1io** [comment]
solved on my own, was dependency topic
