### ISSUE TITLE
Application Enque JSON Codec

### ISSUE THREAD

**Issue by ckrohemb** [chirpstack/chirpstack#667]
Enquing a command via the JSON input fails with an error in the browser console (see below). Enquiing raw hex data works fine. The issue appeared after update to 4.12.

`TypeError: Q.Va is not a function
    Jc google-protobuf.js:22
    serializeBinaryToWriter struct_pb.js:198
    writeMessage google-protobuf.js:472
    serializeBinaryToWriter device_pb.js:7172
    writeMessage google-protobuf.js:472
    serializeBinaryToWriter device_pb.js:7557
    serializeBinary device_pb.js:7541
    H device_grpc_web_pb.js:1079
    fa index.js:64
    be index.js:59
    X index.js:59
    enqueue device_grpc_web_pb.js:1097
    DeviceStore DeviceStore.ts:202
    b DeviceQueue.tsx:208
    onFinish Form.js:77
    u useForm.js:863
    promise callback*u/< useForm.js:859
    onSubmit Form.js:137
    React 11
        gr
        Cr
        kr
        Rs
        Cs
        T
        sp
        ir
        T
        da
        Ki
useForm.js:866:18
`

**Comment by brocaar** [comment]
This has been fixed already, and will be included in the next release (planning this week) (see #658).

**Comment by ckrohemb** [comment]
Thanks! Forgot to check the closed issues ...
